configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/tralahtek%2Fmtn-customer-subscriptions-v2-d7920e9ef7d88234824869d9a520b9ee8be253cb7b18fff8e693ed7be3c48160.yml
